version: '3.9'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: henrybooks
      POSTGRES_USER: henryadmin
      POSTGRES_PASSWORD: securepass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U henryadmin -d henrybooks"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: 1
      DB_NAME: henrybooks
      DB_USER: henryadmin
      DB_PASSWORD: securepass
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
